language: node_js
node_js:
- "9"
before_install: cd backend
before_script:
  - npm install mocha chai
  - npm install request
  - npm start & 
notifications:
  email:
    recipients:
    - iyer.j@husky.neu.edu
    on_success: change
    on_failure: always
